title: Mnseo
description: >-
  Android, 
  What Else?
url: "https://mnseo.github.io"
github: Mnseo
email: mnseoshin@gmail.com
google_analytics: "UA_TOKEN"

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: "Mnseo/Mnseo.github.io"
  issue-term: pathname

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
